behaviors:
  AdaptAgent:
    trainer_type: sac # SAC algorithm for training
    hyperparameters:
      # Hyperparameters common to PPO and SAC
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0003
      learning_rate_schedule: linear

      # SAC-specific hyperparameters
      buffer_init_steps: 0
      tau: 0.005
      steps_per_update: 150.0 # Update roughly every 3 seconds
      save_replay_buffer: false
      init_entcoef: 0.5
      reward_signal_steps_per_update: 150.0

    # Neural network config
    network_settings:
      vis_encode_type: simple
      normalize: false
      hidden_units: 128
      num_layers: 2

    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99

engine_settings:
  time_scale: 1
  no_graphics: false