behaviors:
  AdaptAgent:
    trainer_type: sac  # Change from PPO to SAC
    hyperparameters:
      batch_size: 1024
      buffer_size: 20480
      learning_rate: 0.0003
      tau: 0.005  # Soft update rate for target networks
      steps_per_update: 10  # Number of steps per SAC update
      train_interval: 1  # Train SAC every step
      reward_signal_steps_per_update: 10

    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2

    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0

    max_steps: 5000000
    time_horizon: 128
    summary_freq: 10000
    keep_checkpoints: 5
    checkpoint_interval: 500000

environment_parameters:
  time-scale:
    curriculum:
      - value: 20