behaviors:
  AdaptAgent:  # Replace with the name of your agent behavior
    trainer_type: ppo  # Proximal Policy Optimization 
    hyperparameters:
      batch_size: 1024  # Higher batch size since we have multiple agents
      buffer_size: 20480  # Large enough to hold many agent experiences
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 5000000 # Total training steps
    time_horizon: 128  # How many steps to collect before updating
    summary_freq: 10000  # How often to log results
    keep_checkpoints: 5  # Save last 5 checkpoints
    checkpoint_interval: 500000  # Save model every X steps

environment_parameters:
  time-scale:
    curriculum:
      - value: 5

